remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

title: Birds - Point Count Performance
description: Issues Faced and Remediations
markdown: kramdown
baseurl: "/natureCounts"
url: "https://txnnr.github.io"
